[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node dist/main"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 30
