[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd lms-erp-main/lms-erp/backend && npm install"]

[phases.build]
cmds = ["cd lms-erp-main/lms-erp/backend && npm run build"]

[start]
cmd = "cd lms-erp-main/lms-erp/backend && npm run start:prod"
